name: py${PYTHON}
channels:
- defaults
- conda-forge
dependencies:
  - numpy>=1.11.0
  - pyyaml>=3.12
  - pytest>=3.2.0
  - pytest-cov>=2.3.1
  - python=${PYTHON}
  - cerberus>=1.0.0
  - pint>=0.7.2
  - pandas
  - uncertainties
  - habanero>=0.6.0
  - codecov
  - flake8
