name: py${PYTHON}
channels:
- defaults
- conda-forge
dependencies:
  - numpy>=1.11.0,<2.0
  - pyyaml>=3.12,<4.0
  - pytest>=3.2.0
  - pytest-cov>=2.3.1
  - python=${PYTHON}
  - cerberus>=1.0.0,<1.2
  - pint>=0.7.2,<0.9
  - pandas >=0.22.0,<0.23
  - uncertainties >=3.0.1,<3.1
  - habanero>=0.6.0
  - codecov
  - flake8
