{% set data = load_setup_py_data() %}

package:
  name: pyked
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python
  entry_points:
    - ck2respth = pyked.converters:ck2respth
    - convert_ck = pyked.converters:main
    - respth2ck = pyked.converters:respth2ck

requirements:
  build:
    - python >=3.5
    - setuptools
    - pip

  run:
    - python
    - pyyaml >=3.12,<4.0
    - cerberus >=1.0.0,<1.2
    - pint >=0.7.2,<0.9
    - numpy >=1.11.0,<2.0
    - habanero >=0.6.0,<0.7
    - uncertainties >=3.0.1,<3.1
    - pandas >=0.22.0,<0.23

test:
  imports:
    - pyked

  requires:
    - pytest >=3.2.0
    - pytest-cov >=2.3.1

  commands:
    - pytest -vv --pyargs pyked
    - ck2respth --help
    - respth2ck --help
    - convert_ck --help

about:
  home: data['url']
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD

  summary: data['description']
  description: data['long_description']
  doc_url: https://pr-omethe-us.github.io/PyKED
  dev_url: data['url']
